Repository Lider123/mobile_desiregallery, pull requests merged in 2019-09, with the labels that each got.

#66 Fixed screen orientation
  app/src/main/AndroidManifest.xml
Labels: redesign

#68 Added authentication with VK
  .circleci/config.yml
  .gitignore
  app/build.gradle
  app/my-debug-key.keystore
  app/my-release-key.keystore
  app/src/main/java/com/example/desiregallery/MainApplication.kt
  app/src/main/java/com/example/desiregallery/Utils.kt
  app/src/main/java/com/example/desiregallery/auth/AuthMethod.kt
  app/src/main/java/com/example/desiregallery/auth/EmailAccount.kt
  app/src/main/java/com/example/desiregallery/auth/IAccount.kt
  app/src/main/java/com/example/desiregallery/auth/VKAccount.kt
  app/src/main/java/com/example/desiregallery/sharedprefs/IDGSharedPreferencesHelper.kt
  app/src/main/java/com/example/desiregallery/sharedprefs/PreferencesHelper.kt
  app/src/main/java/com/example/desiregallery/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/SignUpActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/SplashScreenActivity.kt
  app/src/main/java/com/example/desiregallery/ui/dialogs/ChangePasswordDialog.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/FeedFragment.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/SettingsFragment.kt
  app/src/main/res/drawable/button_vk_background.xml
  app/src/main/res/drawable/vk.png
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/vk.properties.sample
Labels: feature

#69 Update README.md
  README.md
Labels: documentation

#73 Refactored auth methods
  app/src/main/java/com/example/desiregallery/auth/AuthMethod.kt
  app/src/main/java/com/example/desiregallery/auth/EmailAccount.kt
  app/src/main/java/com/example/desiregallery/auth/IAccount.kt
  app/src/main/java/com/example/desiregallery/auth/VKAccount.kt
  app/src/main/java/com/example/desiregallery/sharedprefs/PreferencesHelper.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/res/layout/activity_login.xml
Labels: refactor

#76 Added ability to sign in with google account
  app/build.gradle
  app/src/androidTest/java/com/example/desiregallery/LoginInstrumentedTest.kt
  app/src/main/java/com/example/desiregallery/MainApplication.kt
  app/src/main/java/com/example/desiregallery/auth/AuthMethod.kt
  app/src/main/java/com/example/desiregallery/auth/EmailAccount.kt
  app/src/main/java/com/example/desiregallery/auth/GoogleAccount.kt
  app/src/main/java/com/example/desiregallery/auth/IAccount.kt
  app/src/main/java/com/example/desiregallery/auth/VKAccount.kt
  app/src/main/java/com/example/desiregallery/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: feature

#77 Added radio buttons and datepickerdialog to sign up screen
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/SignUpActivity.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/values/strings.xml
Labels: feature, redesign

#78 Added analytics
  app/src/main/java/com/example/desiregallery/MainApplication.kt
  app/src/main/java/com/example/desiregallery/analytics/AnalyticsTracker.kt
  app/src/main/java/com/example/desiregallery/analytics/IDGAnalyticsTracker.kt
  app/src/main/java/com/example/desiregallery/auth/EmailAccount.kt
  app/src/main/java/com/example/desiregallery/presenters/PostPresenter.kt
  app/src/main/java/com/example/desiregallery/ui/activities/FullScreenImageActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/SignUpActivity.kt
  app/src/main/java/com/example/desiregallery/ui/dialogs/PostCreationDialog.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/SettingsFragment.kt
Labels: feature

#79 Added sentry
  .circleci/config.yml
  .gitignore
  app/build.gradle
  app/lint.xml
  app/sentry.properties.sample
  app/src/main/java/com/example/desiregallery/MainApplication.kt
  app/src/main/java/com/example/desiregallery/Utils.kt
  app/src/main/java/com/example/desiregallery/logging/DGLogger.kt
  app/src/main/java/com/example/desiregallery/logging/ILogger.kt
  app/src/main/java/com/example/desiregallery/presenters/PostPresenter.kt
  app/src/main/java/com/example/desiregallery/ui/activities/FullScreenImageActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/LoginActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/SignUpActivity.kt
  app/src/main/java/com/example/desiregallery/ui/dialogs/PostCreationDialog.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/SettingsFragment.kt
  app/src/main/java/com/example/desiregallery/viewmodels/PostListViewModel.kt
Labels: feature

#81 Added signing to release apk
  .circleci/config.yml
  .gitignore
  app/build.gradle
  app/keystore.properties.sample
Labels: feature

#83 Added author to posts
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/desiregallery/adapters/PostAdapter.kt
  app/src/main/java/com/example/desiregallery/auth/GoogleAccount.kt
  app/src/main/java/com/example/desiregallery/models/Post.kt
  app/src/main/java/com/example/desiregallery/models/User.kt
  app/src/main/java/com/example/desiregallery/network/DGNetwork.kt
  app/src/main/java/com/example/desiregallery/network/IQueryApi.kt
  app/src/main/java/com/example/desiregallery/network/query/OrderDirection.kt
  app/src/main/java/com/example/desiregallery/network/query/QueryBody.kt
  app/src/main/java/com/example/desiregallery/network/query/Value.kt
  app/src/main/java/com/example/desiregallery/network/query/filters/CompositeFilter.kt
  app/src/main/java/com/example/desiregallery/network/query/filters/FieldFilter.kt
  app/src/main/java/com/example/desiregallery/network/query/filters/IFilter.kt
  app/src/main/java/com/example/desiregallery/network/query/filters/UnaryFilter.kt
  app/src/main/java/com/example/desiregallery/network/query/operators/ComparisonOperator.kt
  app/src/main/java/com/example/desiregallery/network/query/operators/LogicalOperator.kt
  app/src/main/java/com/example/desiregallery/network/query/operators/UnaryOperator.kt
  app/src/main/java/com/example/desiregallery/network/serializers/PostDeserializer.kt
  app/src/main/java/com/example/desiregallery/network/serializers/PostListDeserializer.kt
  app/src/main/java/com/example/desiregallery/presenters/PostPresenter.kt
  app/src/main/java/com/example/desiregallery/ui/dialogs/ChangePasswordDialog.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/FeedFragment.kt
  app/src/main/java/com/example/desiregallery/ui/views/PostView.kt
  app/src/main/java/com/example/desiregallery/viewmodels/PostListViewModel.kt
  app/src/main/res/drawable/ic_settings_colorsecondary_32dp.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/layout/item_post.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/example/desiregallery/ApiUnitTest.kt
  build.gradle
Labels: feature

#88 Deleted google-services
  .circleci/config.yml
  .gitignore
  app/.gitignore
  app/google-services.json
Labels: security

#89 Updated circle-ci config
  .circleci/config.yml
Labels: security

#93 Refactor comments load
  app/src/main/java/com/example/desiregallery/MainApplication.kt
  app/src/main/java/com/example/desiregallery/Utils.kt
  app/src/main/java/com/example/desiregallery/auth/AccountProvider.kt
  app/src/main/java/com/example/desiregallery/helpers/ModelGenerator.kt
  app/src/main/java/com/example/desiregallery/models/Comment.kt
  app/src/main/java/com/example/desiregallery/models/Post.kt
  app/src/main/java/com/example/desiregallery/models/User.kt
  app/src/main/java/com/example/desiregallery/network/DGNetwork.kt
  app/src/main/java/com/example/desiregallery/network/IDGApi.kt
  app/src/main/java/com/example/desiregallery/network/IQueryApi.kt
  app/src/main/java/com/example/desiregallery/network/errors/CommentError.kt
  app/src/main/java/com/example/desiregallery/network/query/QueryRequest.kt
  app/src/main/java/com/example/desiregallery/network/serializers/CommentDeserializer.kt
  app/src/main/java/com/example/desiregallery/network/serializers/CommentListDeserializer.kt
  app/src/main/java/com/example/desiregallery/network/serializers/CommentSerializer.kt
  app/src/main/java/com/example/desiregallery/network/serializers/PostDeserializer.kt
  app/src/main/java/com/example/desiregallery/network/serializers/PostSerializer.kt
  app/src/main/java/com/example/desiregallery/ui/activities/CommentsActivity.kt
  app/src/main/java/com/example/desiregallery/ui/activities/MainActivity.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/ProfileFragment.kt
  app/src/main/java/com/example/desiregallery/ui/widgets/SnackbarWrapper.kt
  app/src/main/java/com/example/desiregallery/viewmodels/CommentListViewModel.kt
  app/src/main/res/layout/activity_comments.xml
  app/src/main/res/values/strings.xml
  app/vk.properties.sample
Labels: refactor

#87 #85 Post adapter refactoring
  app/build.gradle
  app/src/main/java/com/example/desiregallery/adapters/PostAdapter.kt
  app/src/main/java/com/example/desiregallery/ui/fragments/FeedFragment.kt
  app/src/main/java/com/example/desiregallery/ui/views/PostViewHolder.kt
  app/src/main/res/layout/item_post.xml
Labels: refactor
